# Generated by Django 5.1.15 on 2026-02-10 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_teachers", models.PositiveIntegerField(default=0)),
                ("new_users_today", models.PositiveIntegerField(default=0)),
                ("total_courses", models.PositiveIntegerField(default=0)),
                ("published_courses", models.PositiveIntegerField(default=0)),
                ("total_enrollments", models.PositiveIntegerField(default=0)),
                ("new_enrollments_today", models.PositiveIntegerField(default=0)),
                ("total_quiz_attempts", models.PositiveIntegerField(default=0)),
                ("new_quiz_attempts_today", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "revenue_today",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "daily_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CourseAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("enrollments", models.PositiveIntegerField(default=0)),
                ("completions", models.PositiveIntegerField(default=0)),
                ("avg_progress", models.FloatField(default=0.0)),
                ("avg_quiz_score", models.FloatField(default=0.0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_analytics",
                "ordering": ["-date"],
                "unique_together": {("course", "date")},
            },
        ),
    ]
