# Generated by Django 5.1.15 on 2026-02-10 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=30, help_text="Time limit in minutes (0 = unlimited)"
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=60, help_text="Passing percentage"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = unlimited attempts"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "db_table": "quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text='{"question_id": "selected_answer"}'
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_taken",
                    models.PositiveIntegerField(
                        default=0, help_text="Time taken in seconds"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quiz_attempts",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "quiz"],
                        name="quiz_attemp_student_1efa68_idx",
                    ),
                    models.Index(
                        fields=["quiz", "-completed_at"],
                        name="quiz_attemp_quiz_id_3bcaa1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=500)),
                ("option_b", models.CharField(max_length=500)),
                ("option_c", models.CharField(blank=True, default="", max_length=500)),
                ("option_d", models.CharField(blank=True, default="", max_length=500)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D")],
                        help_text="The correct option letter (a, b, c, or d)",
                        max_length=1,
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField(default=1)),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation shown after answering",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_questions",
                "ordering": ["sequence_number"],
                "unique_together": {("quiz", "sequence_number")},
            },
        ),
    ]
