# Generated by Django 5.1.15 on 2026-02-10 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mathematics", "Mathematics"),
                            ("science", "Science"),
                            ("english", "English"),
                            ("history", "History"),
                            ("computer_science", "Computer Science"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("biology", "Biology"),
                            ("arts", "Arts"),
                            ("music", "Music"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all_levels", "All Levels"),
                        ],
                        db_index=True,
                        default="all_levels",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_covers/%Y/%m/"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Estimated duration e.g. "4 weeks"',
                        max_length=50,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "is_published"],
                        name="courses_teacher_cd37e9_idx",
                    ),
                    models.Index(
                        fields=["category", "level"], name="courses_categor_d7f094_idx"
                    ),
                    models.Index(
                        fields=["is_published", "-created_at"],
                        name="courses_is_publ_454583_idx",
                    ),
                ],
            },
        ),
    ]
