# Generated by Django 5.1.15 on 2026-02-10 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("free", "Free Enrollment")],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("receipt_url", models.URLField(blank=True, default="")),
                ("refund_reason", models.TextField(blank=True, default="")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"], name="payments_student_2f940c_idx"
                    ),
                    models.Index(
                        fields=["course", "status"], name="payments_course__660af1_idx"
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="payments_stripe__6cb0ea_idx",
                    ),
                ],
            },
        ),
    ]
