# Generated by Django 5.1.15 on 2026-02-10 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="Rich text lesson content"
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(db_index=True, default=1),
                ),
                ("video_url", models.URLField(blank=True, default="")),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="lesson_videos/%Y/%m/"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="lesson_files/%Y/%m/"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("video", "Video"),
                            ("pdf", "PDF"),
                            ("document", "Document"),
                            ("presentation", "Presentation"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in minutes"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "db_table": "lessons",
                "ordering": ["sequence_number"],
                "indexes": [
                    models.Index(
                        fields=["course", "sequence_number"],
                        name="lessons_course__2d19b3_idx",
                    )
                ],
                "unique_together": {("course", "sequence_number")},
            },
        ),
    ]
